const messages = {
  home:['Подсветка и управление','Lighting & controls'],time:['Время и будильники','Time & alarms'],settings:['Настройки','Settings'],guide:['Инструкция','Guide'],journal:['Журнал','Log'],
  device:['Электронные часы','Electronic clock'],model:['Четыре лампы IN-12 · деревянный корпус','Four IN-12 tubes · wooden case'],
  subtitle:['Управление по Bluetooth','Bluetooth control'],connect:['Подключить часы','Connect clock'],connected:['Часы подключены','Clock connected'],read:['Прочитать настройки','Read settings'],
  color:['Цвет подсветки','Backlight color'],colorHelp:['Светодиодная подсветка вокруг ламп. Выберите цвет и примените его.','LED lighting around the tubes. Choose a color and apply it.'],customColor:['Произвольный цвет','Custom color'],hue:['Оттенок','Hue'],applyColor:['Применить цвет','Apply color'],colorMode:['Режим подсветки','Backlight mode'],previous:['Предыдущий режим','Previous mode'],next:['Следующий режим','Next mode'],
  remote:['Пульт','Remote control'],remoteHelp:['Кнопки управления меню часов.','Controls for the clock’s built-in menu.'],power:['Питание','Power'],back:['Назад','Back'],plus:['Вперёд','Forward'],minus:['Назад','Backward'],setup:['Настройка','Settings'],confirm:['Подтвердить','Confirm'],remoteNote:['SET открывает меню. + и − меняют пункт или значение, OK подтверждает, «Назад» возвращает на предыдущий уровень.','SET opens the menu. + and − change the item or value, OK confirms, and Back returns to the previous level.'],
  channels:['Каналы подсветки','Backlight channels'],channel:['Канал {n}','Channel {n}'],channelsNote:['Четыре лампы; контроллер приложения поддерживает до шести каналов. Соответствие каналов зависит от прошивки.','Four tubes; the app controller supports up to six channels. Channel mapping depends on the firmware.'],
  pcTime:['Время компьютера','Computer time'],sync:['Установить на часах','Set clock time'],syncHelp:['Передать дату, время и день недели.','Send the date, time and weekday.'],alarms:['Будильники','Alarms'],alarm1:['Будильник 1','Alarm 1'],alarm2:['Будильник 2','Alarm 2'],alarmsHelp:['Укажите время и включите нужный будильник.','Set a time and enable the alarm.'],set:['Задать','Set'],
  schedule:['Расписание','Schedule'],scheduleHelp:['Автоматическое включение и выключение часов.','Automatic clock on/off schedule.'],onTime:['Включать в','Turn on at'],offTime:['Выключать в','Turn off at'],scheduleNote:['Время сохраняется в приложении при изменении. При включении расписания оба времени отправляются на часы, затем включается расписание.','Times are saved in the app when edited. Enabling the schedule sends both times to the clock, then enables the schedule.'],scheduleApply:['Применить расписание','Apply schedule'],scheduleSaved:['Выбранный интервал: {on} — {off}','Selected interval: {on} — {off}'],scheduleEmpty:['Задайте оба времени.','Enter both times.'],scheduleSent:['Отправлено: {on} — {off} · ещё не подтверждено','Sent: {on} — {off} · not yet confirmed'],scheduleRead:['Последний ответ часов: {on} — {off}','Last clock reply: {on} — {off}'],
  autoSync:['Следовать времени компьютера','Follow computer time'],autoSyncHelp:['Обновлять время каждую секунду, пока приложение открыто и часы подключены.','Update the time every second while the app is open and the clock is connected.'],autoSyncNote:['Действует только в текущем подключении.','Applies to the current connection only.'],
  featureA:['Автоматическая яркость','Automatic brightness'],descA:['Яркость в зависимости от освещения. Ручной режим и 10 уровней яркости доступны в меню часов, пункт 06.','Brightness based on ambient light. Manual mode and 10 brightness levels are available in clock menu 06.'],
  featureC:['Датчик освещения','Ambient light sensing'],descC:["Действие этого переключателя на модели IN12_M4 не установлено. Для подстройки яркости к освещению используйте «Автоматическая яркость». Для периодического перебора цифр откройте пункт 16 меню часов — «Защита ламп».", "The effect of this switch on the IN12_M4 has not been established. Use Automatic brightness to adjust brightness to room lighting. For periodic digit cycling, use clock menu 16, Tube protection."],
  featureF:['Включение по датчику','Sensor-controlled switching'],descF:["Переключатель управления от датчика. Тип датчика и условия включения для IN12_M4 не описаны производителем; поведение может зависеть от версии часов.", "A switch for sensor-based control. The manufacturer does not describe the sensor type or activation conditions for the IN12_M4; behavior may vary by clock version."],
  featureB:['12-часовой формат','12-hour format'],descB:['Выключите для 24-часового формата. На самих часах это пункт меню 09.','Turn off for the 24-hour format. This is clock menu 09.'],
  featureD:['Объявление времени каждый час','Hourly time announcement'],descD:['Голосовое объявление в начале часа. Ночной режим в меню 12 может отключать его при низкой яркости.','Voice announcement at the start of each hour. Night mode in menu 12 can suppress it at low brightness.'],
  featureE:['Английская озвучка часов','English clock voice'],descE:['Язык голосовых сообщений часов: включено — английский, выключено — китайский. Язык приложения выбирается отдельно.','Clock voice language: on is English, off is Chinese. The app language is selected separately.'],
  protection:['Защита ламп','Tube protection'],protectionShort:['Периодический перебор цифр — отдельная функция, пункт меню 16. Рекомендуемый интервал: 5 минут.','Periodic digit cycling is a separate function, clock menu 16. Recommended interval: 5 minutes.'],how:['Как настроить','How to set it'],
  unread:['Не прочитано','Not read'],unknown:['Не определено','Unknown'],on:['Включено','On'],off:['Выключено','Off'],fromClock:['Ответ часов','Clock reply'],pending:['Отправлено, не подтверждено','Sent, not confirmed'],rawUnknown:['Ответ «{raw}» не расшифрован','Reply “{raw}” is not decoded'],lastReply:['Последний ответ','Last reply'],selected:['Выбрано: {color}','Selected: {color}'],colorValue:['Цвет: {color}','Color: {color}'],readAt:['Прочитано в {time}','Read at {time}'],stale:['соединение закрыто','disconnected'],invalidTime:['Часы вернули некорректное время: {value}','Clock returned an invalid time: {value}'],timeReply:['С часов: {value}','Clock: {value}'],timeSent:['Отправлено: {value} · не подтверждено','Sent: {value} · not confirmed'],
  saveLog:['Сохранить журнал','Save log'],logHelp:['TX — отправленная команда, RX — ответ часов. Пароль не записывается.','TX is a sent command; RX is a clock reply. The password is not logged.'],noEvents:['Пока нет событий.','No events yet.'],saved:['Сохранено: {path}','Saved: {path}'],sending:['Передаём команду…','Sending command…'],failed:['Не удалось выполнить действие','Action failed'],runApp:['Запустите Guoran Clock для подключения к часам.','Run Guoran Clock to connect to the clock.'],lost:['Связь с приложением прервана: {error}','Connection to the app lost: {error}'],
  connectHelp:['Включите часы рядом с компьютером. Их Bluetooth-имя начинается с XGGF, например XGGF-IN1204240430.4.','Power on the clock near your computer. Its Bluetooth name starts with XGGF, for example XGGF-IN1204240430.4.'],connectNote:['Закройте другое приложение, если оно уже подключено к часам.','Close any other app that is already connected to the clock.'],scan:['Найти часы','Find clock'],enableBt:['Включить Bluetooth','Enable Bluetooth'],scanPrompt:['Нажмите «Найти часы»','Click “Find clock”'],scanning:['Идёт поиск…','Searching…'],unnamed:['Без имени','Unnamed'],password:['Пароль подключения','Connection password'],passwordHint:['Пароль из исходного приложения: 210709','Original app password: 210709'],disconnect:['Отключить','Disconnect'],connectAction:['Подключиться','Connect'],close:['Закрыть','Close'],
  lightTheme:['Светлая тема','Light theme'],darkTheme:['Тёмная тема','Dark theme'],language:['Язык приложения','App language'],
  amber:['Янтарный','Amber'],warm:['Тёплый белый','Warm white'],coral:['Коралловый','Coral'],lavender:['Лавандовый','Lavender'],sky:['Голубой','Sky blue'],teal:['Бирюзовый','Teal'],sage:['Зелёный','Green'],white:['Белый','White'],
  guideIntro:["Руководство по управлению часами IN12_M4. Настройки можно менять с компьютера по Bluetooth или кнопками на корпусе.", "IN12_M4 clock user guide. Change settings from a computer over Bluetooth or with the buttons on the case."],
  guideMenu:['Меню настроек','Settings menu'],guideMenuText:['Нажмите SET в разделе «Подсветка и управление» или одновременно L и R на корпусе. Две левые лампы показывают код пункта, две правые — его значение. Кнопками +/− выберите пункт, нажмите OK, измените значение и подтвердите OK. «Назад» возвращает на предыдущий уровень; в главном меню выходит из настройки. Следите за индикацией и голосовыми подсказками часов.','Press SET under Lighting & controls, or press L and R on the case together. The left two tubes show the menu code; the right two show its value. Use +/− to select an item, press OK, change its value and confirm with OK. Back returns one level and exits settings from the main menu. Follow the clock display and voice prompts.'],
  guideProtection:["Защита ламп периодически перебирает все цифры. Это нормальная работа часов. Чтобы задать интервал, нажмите SET, выберите слева пункт 16 кнопками + / − и нажмите OK. Справа выберите интервал от 5 до 15 минут и подтвердите OK. Рекомендуется 5 минут. Значение 0 отключает защиту; производитель не рекомендует её отключать.", "Tube protection periodically cycles through all digits. This is normal operation. To set the interval, press SET, select item 16 on the left with + / − and press OK. Select an interval of 5 to 15 minutes on the right and confirm with OK. The recommended interval is 5 minutes. Value 0 disables protection; the manufacturer recommends keeping it enabled."],
  guideTouch:['Кнопки на корпусе','Case buttons'],guideTouchText:['L включает/выключает подсветку, в меню увеличивает значение. OK включает/выключает часы, в меню подтверждает выбор. R показывает дату, в меню уменьшает значение. L+R — вход/выход из настроек; OK+R — таймер.','L toggles the backlight and increases values in the menu. OK toggles the clock and confirms menu choices. R displays the date and decreases menu values. L+R enters/exits settings; OK+R starts the timer.'],
  guideRead:['Чтение и отправка','Reading and sending'],guideReadText:['«Ответ часов» — полученное значение. «Отправлено, не подтверждено» — команда передана, но новый ответ ещё не получен. «Прочитать настройки» запрашивает ответ; если часы молчат, приложение переподключается. Необычные значения показаны отдельно и не мешают остальным функциям.','“Clock reply” is a received value. “Sent, not confirmed” means the command was sent but no new reply has arrived. Read settings requests a reply and reconnects if the clock does not respond. Unusual values are shown separately and do not block the remaining controls.'],
  guidePower:['Питание и уход','Power & care'],guidePowerText:['По инструкции: питание DC 5 В, потребление менее 400 мА, размеры 132 × 50 × 50 мм. Держите часы в сухом месте, не тяните за USB-разъём и не разбирайте корпус.','Manual specifications: DC 5 V, current below 400 mA, dimensions 132 × 50 × 50 mm. Keep the clock dry, avoid pulling on the USB connector, and do not open the case.'],
  menuTable:['Пункты меню часов','Clock menu reference'],code:['Код','Code'],function:['Функция','Function'],values:['Значения','Values'],
};
Object.assign(messages, {
 quickStart:['Первое подключение','First connection'],
 quickStartText:['Подключите часы к питанию 5 В и включите Bluetooth на компьютере. Нажмите «Подключить часы» → «Найти часы» и выберите имя, начинающееся с XGGF. Введите пароль подключения (по умолчанию 210709) и нажмите «Подключиться». Если часы заняты другим приложением, отключите их в нём. После подключения откройте раздел «Подсветка и управление».','Connect the clock to a 5 V power supply and enable Bluetooth on the computer. Click Connect clock → Find clock and select a name starting with XGGF. Enter the connection password (default 210709), then click Connect. Disconnect any other app using the clock. Once connected, open Lighting & controls.'],
 diagramTitle:['Пример выбора будильника 1','Example: selecting alarm 1'],
 diagramItem:['SET · выбор пункта','SET · select item'],diagramValue:['OK · выбор значения','OK · select value'],
 diagramCaption:['Схема индикации: выделенная рамкой пара — активная. Это пример, а не показания подключённых часов.','Display diagram: the outlined pair is active. This is an example, not a live clock reading.'],
 menuOpen:['Таблица пунктов меню','Show menu reference'], menuClose:['Скрыть таблицу','Hide reference'],
 menuLeft:['Слева: пункт','Left: menu item'], menuRight:['Справа: значение','Right: value'],
 menuStep1:['1. Нажмите SET. Подсвечивается левая пара ламп — код пункта в колонке «Слева: пункт». Кнопками + / − выберите пункт.','1. Press SET. The left pair lights up: its code is in the “Left: menu item” column. Select an item with + / −.'],
 menuStep2:['2. Нажмите OK. Выбор переходит на правую пару ламп — значение из колонки «Справа: значение». Измените его кнопками + / −.','2. Press OK. Selection moves to the right pair: use the “Right: value” column. Change the value with + / −.'],
 menuStep3:['3. Подтвердите значение кнопкой OK. Некоторые пункты открывают дальнейшую настройку, например время будильника. «Назад» возвращает на предыдущий уровень; из главного меню — к часам.','3. Confirm with OK. Some items open further settings, such as the alarm time. Back returns one level, or exits the main menu to the clock.'],
 menuExample:["Пример: код 02 слева означает «Будильник 1». Нажмите OK: выбор перейдёт направо. Значение 0 означает «выключен», 1 — «включён» с дальнейшей настройкой времени. Подсветка показывает активную пару ламп.", "Example: code 02 on the left means Alarm 1. Press OK to move selection to the right. Value 0 means off; 1 means on, followed by alarm time setup. Highlighting identifies the active pair of tubes."],
 menuPrepare:["Для входа в меню нажмите SET. Приложение сначала выполняет «Назад», затем SET: так часы выходят из текущего режима перед выбором пункта.", "Press SET to enter the menu. The app sends Back first, then SET, so the clock leaves its current mode before menu selection."],
 menuReferenceOnly:['Таблица — справочник. Открытие и закрытие таблицы не отправляет команды. Текущий пункт смотрите на лампах часов.','This is a reference. Showing or hiding it sends no commands. Read the current selection on the clock tubes.']
});
messages.remoteNote = ['SET: выбрать пункт слева → OK: выбрать значение справа → OK: подтвердить. + / − меняют выбранный код.', 'SET: select the left item → OK: select the right value → OK: confirm. + / − change the selected code.'];
messages.guideMenuText = ['Пульт работает в два этапа: сначала выбирается пункт меню на двух левых лампах, затем его значение на двух правых. На корпусе вход в настройки — одновременное нажатие L и R.', 'The remote works in two stages: select a menu item on the left two tubes, then its value on the right two. On the case, press L and R together to enter settings.'];
messages.code = messages.menuLeft;
messages.values = messages.menuRight;
const menuRows = [
 ['01',['Установка времени','Time setting'],['0 — вручную; 1 — синхронизация по Bluetooth','0 — manual; 1 — Bluetooth synchronization']],
 ['02 / 03',['Будильники 1 / 2','Alarms 1 / 2'],['0 — выключен; 1 — включён и настройка времени','0 — off; 1 — on and set alarm time']],
 ['04',['Смена цифр','Digit transitions'],['0–3 — эффекты смены цифр','0–3 — digit transition effects']],
 ['05',['Двоеточие','Colon'],['0 — выключено; 1 — включено','0 — off; 1 — on']],
 ['06',['Яркость','Brightness'],['0 — автоматически; 1 — ручная регулировка, 10 уровней','0 — automatic; 1 — manual adjustment, 10 levels']],
 ['07',['Громкость','Volume'],['0–7; 0 — без звука','0–7; 0 — silent']],
 ['08',['Режим отображения','Display mode'],['1 — часы/минуты/секунды; 2 — часы/минуты/день недели; 3 — месяц/день/день недели; 4 — свой режим','1 — hours/minutes/seconds; 2 — hours/minutes/weekday; 3 — month/day/weekday; 4 — custom']],
 ['09',['Формат времени','Time format'],['12 или 24 часа','12 or 24 hours']],
 ['10',['Расписание','Schedule'],['1 — время включения; 2 — время выключения','1 — turn-on time; 2 — turn-off time']],
 ['11',['Объявление часа','Hourly announcement'],['0 — выключено; 1 — включено','0 — off; 1 — on']],
 ['12',['Ночной режим','Night mode'],['0 — выключен; 1 — без объявления времени при яркости ниже 2','0 — off; 1 — suppress time announcements below brightness level 2']],
 ['13',['Мелодия будильника','Alarm sound'],['1–6 — выбор мелодии','1–6 — select sound']],
 ['14',['Цвет подсветки по дням недели','Weekday backlight colors'],['0 — выключено; 1 — включено (ручная смена цвета недоступна)','0 — off; 1 — on (manual color changes unavailable)']],
 ['15',['Внешний выключатель','External switch'],['0 / 1 — резервный интерфейс для внешних устройств','0 / 1 — reserved interface for external devices']],
 ['16',['Защита ламп','Tube protection'],['0 — выключена; 5–15 минут; рекомендовано 5','0 — disabled; 5–15 minutes; 5 recommended']],
 ['17',['Язык озвучки','Voice language'],['0 — китайский; 1 — английский','0 — Chinese; 1 — English']],
 ['18',['Сброс часов','Reset clock'],['00 — не сбрасывать; 11 — заводские настройки','00 — keep settings; 11 — restore factory settings']]
];
let language='ru';
function t(key,vars={}){let text=messages[key]?.[language==='en'?1:0]??key;for(const [k,v] of Object.entries(vars))text=text.replaceAll('{'+k+'}',String(v));return text;}
const serverMessages=/*__ERRORS__*/{};
function translateError(text){return language==='en'?(serverMessages[text]||text):text;}
